services:
  youtube-mcp-server:
    build: .
    ports:
      - "14000:3000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    depends_on:
      - pot-provider

  pot-provider:
    image: brainicism/bgutil-ytdlp-pot-provider
    # ports:
    #   - "4416:4416"
    restart: unless-stopped
